# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    #xcversion(version: "15.0.1")
    api_key = app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['KEY_CONTENT']
    )

    sync_code_signing(
      api_key: api_key,
      type: "appstore",
      readonly: false,
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      xcargs: "-allowProvisioningUpdates",
    )

    upload_to_testflight(api_key: api_key,)
  end
end
